name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  update-git-tag: # Reason: <https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations>
    name: Update latest major git tag
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run this action
        uses: ./
        id: slug

      - name: Setup git
        run: |
          git config --local user.email 'actions@github.com'
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git"

      - name: Create tag
        run: git tag -fa "v${{ steps.slug.outputs.version-major }}" -m "Update v${{ steps.slug.outputs.version-major }} tag (using GitHub actions)"

      - name: Push tag
        run: git push --set-upstream origin "v${{ steps.slug.outputs.version-major }}" --force
